import { FC } from "react";
import Footer from "@/_components/Footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const ShopLayout: FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default ShopLayout;