import { FC } from 'react';
import { ThemeProvider } from '@/_contexts/ThemeContext';
import Header from "@/_components/Header";
import Footer from "@/_components/Footer";
import '@/_styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;