import { FC } from 'react';
import '@/_styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const ErrorLayout: FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
};

export default ErrorLayout;